config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

# Admin site
admin.site.site_header = 'WDS_STORE'

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # Your stuff: custom urls includes go here
    path('', include(('wds_store.shirts.urls', 'shirts'), namespace='items')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar # type:ignore

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

wds_store/shirts/urls.py
"""."""

# Django
from django.urls import path 
from django.urls.exceptions import NoReverseMatch

# Views
from wds_store.shirts import views


urlpatterns = [
    # Personal_admin
    path(
        route = 'personal_admin/menu/',
        view = views.Menu.as_view(),
        name = "menu"
    ),
    path(
        route = "personal_admin/menu/crear/<str:modelo>/<str:slugname>/",
        view = views.CreateView.as_view(),
        name = "create"
    ),
    path(
        route = "personal_admin/menu/itemlist/<str:modelo>/<str:objeto>/",
        view = views.ItemList.as_view(),
        name = "itemlist"
    ),
    path(
        route = "personal_admin/menu/delete/<str:modelo>/<str:objeto>/",
        view = views.DeleteView.as_view(),
        name = "delete"
    ),
    path(
        route = "personal_admin/menu/update/<str:modelo>/<str:objeto>/<str:slugname>/",
        view = views.UpdateView.as_view(),
        name = "update"
    )
]

wds_store/extras/forms.py
"""Validaciones basadas en formularios para el admin."""

# Django
from django import forms

# Utils
from collections import Counter

from django.core.exceptions import ObjectDoesNotExist
from django.forms.forms import Form

# Models
from .models import Color, Talla

# ------------------------------------------ end ---------------------------------------------------

# Form camisa
class CamisaForm(forms.ModelForm):
    def clean(self):
        try:
            self.cleaned_data['talla']
        except (KeyError):
            raise forms.ValidationError('Asegurece de completar todos los campos requeridos antes de guardar.')
        if self.instance.id == None:
            self.instance.save()

# ------------------------------------------ end ----------------------------------------------------

class InlineImageneFormSet(forms.BaseInlineFormSet):
    def clean(self):
        """Limitaciones en el orden del inline."""
        if self.instance.id == None:
            return
        recolector_imagen_principal = []
        recolector_color_imagen = []
        # Validaciones
        try:
            for data in self.cleaned_data:
            
                # Imagen principal
                if data['DELETE'] != True:
                    recolector_imagen_principal.append(data['imagen_principal'])
                    recolector_color_imagen.append(data['color'])
                contador_imagen_principal = Counter(recolector_imagen_principal)
                contador_color_imagen = Counter(recolector_color_imagen)
                imagen_principal_error = False
                imagen_principal_error = [
                    True for afirmacion in list(contador_imagen_principal.items()) if afirmacion[0] == 'SI' and afirmacion[1] > 1
                ]
                if imagen_principal_error:
                    raise forms.ValidationError('No puedes tener dos o mas imagenes principales.')
                
                #...
                if data == self.cleaned_data[-1]:
                    if not 'SI' in recolector_imagen_principal:
                        raise forms.ValidationError('Necesitas seleccionar al menos una IMAGEN que no vayas a eliminar como PRINCIPAL.')
            if len(self.forms) == 0:
                raise KeyError
        except (KeyError, AttributeError):
            raise forms.ValidationError('Asegurece de completar todos los campos requeridos antes de guardar.')
        # Validacion repetir imagen ---
        for primero in range(len(self.forms)):
                v = primero + 1
                for segundo_enadelante in range(len(self.forms)):
                    try:
                        if self.forms[primero].cleaned_data['imagen'] == self.forms[v].cleaned_data['imagen']:
                            raise forms.ValidationError('No puedes poner dos o mas veces la misma imagen. Por favor elige una diferente donde se encontraba alguna de las repetidas.')
                    except (IndexError):
                        continue
                    v += 1
        # Orden y Color (contador_color_imagen)
        lista_color_y_cantidad_imagenes = contador_color_imagen.items() # type:ignore
        for color_y_cantidad in lista_color_y_cantidad_imagenes:
            orden = 0
            for form in range(len(self.forms)):
                if orden == color_y_cantidad[1]:
                    break
                if self.forms[form].cleaned_data['color'] == color_y_cantidad[0] and self.forms[form].cleaned_data['DELETE'] == False:
                    self.forms[form].cleaned_data['orden'] = orden
                    self.forms[form].instance.orden = orden
                    orden += 1
                    
        # Delete
        for form in range(len(self.forms)):
            if self.forms[form].cleaned_data['DELETE']:
                #print(self.forms[form].instance, ' : ', self.forms[form].instance.color, ' : ', self.forms[form].instance.orden, ' : ', self.forms[form].cleaned_data['DELETE']) 
                self.forms[form].instance.delete()
                self.instance.colores.remove(self.forms[form].instance.color)
        # Save
        for form in range(len(self.forms)):
            if not self.forms[form].cleaned_data['DELETE']:
                #print(self.forms[form].instance, ' : ', self.forms[form].instance.color, ' : ', self.forms[form].instance.orden, ' : ', self.forms[form].cleaned_data['DELETE']) 
                self.forms[form].instance.save()
                self.instance.colores.add(self.forms[form].instance.color)

# ----------------------------------------------- end --------------------------------------------

# Form color
class ColorForm(forms.ModelForm):

    def clean(self):
        capitalize = self.cleaned_data['color'].capitalize()
        self.cleaned_data['color'] = capitalize
        self.instance.color = capitalize
        try:
            if Color.objects.get(color=capitalize):
                raise forms.ValidationError('Este color ya ha sido registrado antes.')
        except (ObjectDoesNotExist):
            return super().clean()

# ----------------------------------------------- end --------------------------------------------

# Form talla
class TallaForm(forms.ModelForm):

    def clean(self):
        capitalize = self.cleaned_data['talla'].capitalize()
        tallas = Talla.objects.all()
        for talla in tallas:
            if talla.talla.capitalize() == capitalize and self.instance.id != talla.id:
                raise forms.ValidationError('Esta talla ya ha sido registrada antes.')
        return super().clean()

wds_store/shirts/forms.py
"""."""

# Django
from wds_store.shirts.models import Producto
from django import forms

class ProductoCreateForm(forms.Form):
    """."""
    producto = forms.CharField(
        min_length=2, 
        max_length=20,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Ingrese un tipo de producto'
            }
        )
    )

    def save(self):
        data = self.cleaned_data

        producto = Producto.objects.create(**data)

wds_store/shirts/views.py
"""."""

# Django
from wds_store.extras.models import Imagenes
from django.urls import (
    reverse_lazy,
    reverse
)
from django.views.generic import (
    TemplateView,
    DeleteView,
    CreateView,
    UpdateView
)

# Models
from wds_store.shirts.models import (
    Celebration, 
    Item,
    Producto,
    Color, Talla
)

class Menu(TemplateView):
    """."""
    template_name = "menu/index&listados.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['productos'] = Producto.objects.all()
        context['celebraciones'] = Celebration.objects.all()
        context['colores'] = Color.objects.all()
        context['items'] = Item.objects.all()
        return context

# ------------------------------------------ end category -----------------------------------------

class ItemList(TemplateView):
    """."""
    template_name = "menu/filtrar_items.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['options'] = False
        if kwargs['modelo'] == 'producto':
            producto = Producto.objects.get(nombre=kwargs['objeto'])
            context['tallas'] = Talla.objects.filter(producto=producto)
            context['items'] = Item.objects.filter(producto=producto)
            context['imagenes'] = Imagenes.objects.filter(imagen_principal='SI')
            context['objeto'] = kwargs['objeto']
        if kwargs['modelo'] == 'celebracion':
            celebracion = Celebration.objects.get(nombre=kwargs['objeto'])
            context['items'] = Item.objects.filter(celebracion=celebracion)
            context['imagenes'] = Imagenes.objects.filter(imagen_principal='SI')
        if kwargs['modelo'] == 'color':
            color = Color.objects.get(nombre=kwargs['objeto'])
            context['imagenes'] = Imagenes.objects.filter(color=color, orden=0)
            context['modelo'] = 'imagen'
        if kwargs['modelo'] == 'talla':
            talla = Talla.objects.get(talla=kwargs['objeto'])
            context['items'] = Item.objects.filter(talla=talla)
            context['imagenes'] = Imagenes.objects.filter(imagen_principal='SI')
            context['modelo'] = 'Item'
            context['objeto'] = kwargs['objeto']
        return context

# ------------------------------------------ end category -----------------------------------------

class DeleteView(DeleteView):
    """."""
    template_name = "menu/confirm_delete.html"

    def get_object(self):
        if self.kwargs['modelo'] == 'producto':
            objeto = Producto.objects.get(nombre=self.kwargs['objeto'])
        if self.kwargs['modelo'] == 'celebracion':
            objeto = Celebration.objects.get(nombre=self.kwargs['objeto'])
        if self.kwargs['modelo'] == 'color':
            objeto = Color.objects.get(nombre=self.kwargs['objeto'])
        if self.kwargs['modelo'] == 'talla':
            objeto = Talla.objects.get(talla=self.kwargs['objeto'])
        return objeto
    
    def get_success_url(self):
        if self.kwargs['modelo'] == 'producto':
            modelo = 'productos'
        if self.kwargs['modelo'] == 'celebracion':
            modelo = 'celebraciones'
        if self.kwargs['modelo'] == 'color':
            modelo = 'colores'
        if self.kwargs['modelo'] == 'talla':
            modelo = 'tallas'
        return reverse('items:menu')

# ------------------------------------------ end category -----------------------------------------

class UpdateView(UpdateView):
    """."""
    template_name = "menu/create&update.html"

    def get_object(self):
        if self.kwargs['modelo'] == 'producto':
            objeto = Producto.objects.get(nombre=self.kwargs['objeto'])
        if self.kwargs['modelo'] == 'celebracion':
            objeto = Celebration.objects.get(nombre=self.kwargs['objeto'])
        if self.kwargs['modelo'] == 'color':
            objeto = Color.objects.get(nombre=self.kwargs['objeto'])
        if self.kwargs['modelo'] == 'talla':
            objeto = Talla.objects.get(talla=self.kwargs['objeto'])
        return objeto
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.kwargs['modelo'] == 'producto':
            context['modelo'] = 'Producto'
        if self.kwargs['modelo'] == 'celebracion':
            context['modelo'] = 'Celebracion'
        if self.kwargs['modelo'] == 'color':
            context['modelo'] = 'Color'
        if self.kwargs['modelo'] == 'talla':
            context['modelo'] = 'Talla'
            context['productos_checked'] = [producto.nombre for producto in self.object.producto.all()]
            context['slugname'] = self.kwargs['slugname']
            context['list'] = Producto.objects.all()
        return context
    
    def get_form_class(self):
        if self.kwargs['modelo'] == 'talla':
            fields = ['talla','orden','producto']
            self.fields = fields
        else:
            fields = ['nombre']
            self.fields = fields
        return super().get_form_class()
    
    def get_success_url(self):
        if self.kwargs['modelo'] in ['producto', 'celebracion', 'color', 'talla']:
            if self.kwargs['modelo'] == 'producto':
                modelo = 'productos'
                slugname = self.kwargs['objeto']
            if self.kwargs['modelo'] == 'celebracion':
                modelo = 'celebraciones'
                slugname = self.kwargs['objeto']
            if self.kwargs['modelo'] == 'color':
                modelo = 'colores'
                slugname = self.kwargs['objeto']
            if self.kwargs['modelo'] == 'talla':
                modelo = 'tallas'
                slugname = self.kwargs['slugname']
            return reverse('items:menu')

# ------------------------------------------ end category -----------------------------------------

class CreateView(CreateView):
    """."""
    template_name = "menu/create&update.html"

    def get_queryset(self):
        if self.kwargs['modelo'] == 'producto':
            queryset = Producto.objects.all()
        if self.kwargs['modelo'] == 'celebracion':
            queryset = Celebration.objects.all()
        if self.kwargs['modelo'] == 'color':
            queryset = Color.objects.all()
        if self.kwargs['modelo'] == 'item':
            queryset = Item.objects.all()
        if self.kwargs['modelo'] == 'talla':
            queryset = Talla.objects.all()
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.kwargs['modelo'] == 'producto':
            context['modelo'] = 'Producto'
        if self.kwargs['modelo'] == 'celebracion':
            context['modelo'] = 'Celebracion'
        if self.kwargs['modelo'] == 'color':
            context['modelo'] = 'Color'
        if self.kwargs['modelo'] == 'talla':
            context['modelo'] = 'Talla'
            context['slugname'] = self.kwargs['slugname']
            context['list'] = Producto.objects.all()
        if self.kwargs['modelo'] == 'item':
            context['modelo'] = 'Item'
            context['slugname'] = Producto.objects.get(nombre=self.kwargs['slugname'])
            context['tallas'] = Talla.objects.filter(producto=context['slugname'])
            context['celebraciones'] = Celebration.objects.all()
        return context
    
    def get_form_class(self):
        if self.kwargs['modelo'] == 'talla':
            fields = ['talla', 'orden', 'producto']
            self.fields = fields
        if self.kwargs['modelo'] in ['producto', 'celebracion', 'color']:
            fields = ['nombre']
            self.fields = fields
        if self.kwargs['modelo'] == 'item':
            fields = ['producto', 'publico', 'talla', 'celebracion']
            self.fields = fields
        return super().get_form_class()

    def get_success_url(self):
        if self.kwargs['modelo'] in ['producto', 'celebracion', 'color', 'talla']:
            if self.kwargs['modelo'] == 'producto':
                modelo = 'productos'
                slugname = self.kwargs['slugname']
            if self.kwargs['modelo'] == 'celebracion':
                modelo = 'celebraciones'
                slugname = self.kwargs['slugname']
            if self.kwargs['modelo'] == 'color':
                modelo = 'colores'
                slugname = self.kwargs['slugname']
            if self.kwargs['modelo'] == 'talla':
                modelo = 'tallas'
                slugname = self.kwargs['slugname']
            return reverse('items:menu')
        if self.kwargs['modelo'] in ['item', 'imagen']:
            return reverse('items:menu')


# ------------------------------------------ end category -----------------------------------------

wds_store/templates/menu/confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <form method="POST">
      {% csrf_token %}
      <div class="media" style="background-color: white;">
        <div class="media-body">
            <button class="btn btn-danger" type="submit">Yes, DO IT</button>
        </div>
        <div class="media-body">
            <a class="btn btn-success" href="{% url 'items:menu' %}">No, DON'T DO IT</a>
        </div>
      </div>
  </form>
{% endblock content %}

wds_store/templates/menu/create&update.html
{% extends "base.html" %}

{% block content %}
  
  {% if modelo == 'Talla' %}
    <div class="media">
      <form method="POST">
          {% csrf_token %}
          <div class="media">
            <div class="form-group">
              <label style="color: yellow;">{{ modelo }}</label>
              <input class="form-control" type="text" placeholder="Talla" name="talla" value="{{talla.talla}}" required>
            </div>
            <div class="form-group">
              <label style="color: yellow;">Orden</label>
              <input class="form-control" type="number" min=0 value="0" placeholder="Orden" name="orden">
            </div>
            <div class="form-group">
            <label style="color: yellow;">Productos</label>
              {% for objeto in list %}
                <div class="form-group">
                  {% if objeto.nombre == slugname %}
                    <input type="checkbox" name="producto" checked required value="{{objeto.id}}">
                  {% elif objeto.nombre in productos_checked %}
                    <input type="checkbox" name="producto" checked value="{{objeto.id}}">
                  {% else %}
                    <input type="checkbox" name="producto" value="{{objeto.id}}">
                  {% endif %}
                  <label style="color: aliceblue;">{{objeto.nombre}}</label>
                </div>
              {% endfor %}
            </div>
            <div class="media-body">
              <button class="btn btn-warning" type="submit">Up!</button>
            </div>
          </div>
      </form>
    </div>
  {% else %}
    <div class="media">
      <form method="POST">
          {% csrf_token %}
          <div class="media">
            <div class="form-group">
              <label style="color: yellow;">{{ modelo }}</label>
              {% if modelo == 'Celebracion' %}
                <input class="form-control" type="text" placeholder="Nombre" name="nombre" value="{{celebration.nombre}}">
              {% endif %}
              {% if modelo == 'Producto' %}
                <input class="form-control" type="text" placeholder="Nombre" name="nombre" value="{{producto.nombre}}">
              {% endif %}
              {% if modelo == 'Color' %}
                <input class="form-control" type="text" placeholder="Nombre" name="nombre" value="{{color.nombre}}">
              {% endif %}
              {% if modelo == 'Item' %}
                <h1><strong>{{ slugname }} {{ slugname.id }}</strong></h1>
                <input type="hidden" value="slugname.id" name="producto">
                <label style="color: yellow;">Tallas</label>
                <select class="js-select form-control-lg mr-sm-2" name="talla" multiple>
                  {% for talla in tallas %}
                    <option value="{{ talla.id }}">{{ talla }}</option>
                  {% endfor %}
                </select>
                <label style="color: yellow;">Celebracion</label>
                <select class="js-select form-control-lg mr-sm-2" name="celebracion">
                  <option></option>
                  {% for celebracion in celebraciones %}
                    <option value="{{ celebracion.id }}">{{ celebracion }}</option>
                  {% endfor %}
                </select>
                <label style="color: yellow;">Publico</label>
                <select class="js-select" name="publico">
                    <option value="HOMBRE">Hombre</option>
                    <option value="MUJER">Mujer</option>
                    <option value="NIÑA">Niña</option>
                    <option value="NIÑO">Niño</option>
                </select>
                <fieldset class="module">
                  <h2>Imagenes del producto</h2>
                  <table>
                    <thead>
                      <tr>
                        <th class="original"></th>
                        <th class="column-image required">Imagen</th>
                        <th class="column-color required">Color</th>
                        <th class="column-orden">Orden</th>
                        <th class="column-image_principal required">Imagen principal</th>
                        <th>Delete?</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr class="form-row row1 empty-form" id="images_set-empty">
                        <td class="original">
                          <input type="hidden" name="imagenes_set-___prefix__-id" id="id_imagenes_set-__prefix__-id">
                          <input type="hidden" name="imagenes_set-__prefix__-item" id="id_imagenes_set-__prefix__-item">
                        </td>
                        <td class="field-imagen">
                          <div class="form-group">
                            <input type="file" hidden name="imagenes_set-__prefix__-imagen" accept="imagen/*" id="id_imagenes_set-__prefix__-imagen">
                            <label for="id_imagenes_set-__prefix__-imagen"><img src=""></label>
                          </div>
                        </td>
                        <td class="field-color">
                          <div class="related-widget-wrapper">
                            <select name="imagenes_set-__prefix__-color" id="id_imagenes_set-__prefix__-color">
                              <option value selected>---------</option>
                            </select>
                          </div>
                        </td>
                        <td class="field-orden">
                          <input type="number" name="imagenes_set-__prefix__-orden" class="vIntegerField" min="0" id="id_imagenes_set-__prefix__-orden">
                        </td>
                        <td class="field-imagen_principal">
                          <select name="imagenes_set-__prefix__-imagen_principal" id="id_imagenes_set-__prefix__-imagen_principal">
                            <option value="NO" selected>No</option>
                            <option value="SI">Si</option>
                          </select>
                        </td>
                        <td class="delete"></td>
                      </tr>
                      <tr class="add-row">
                        <td colspan="6">
                          <a href="#">Add another image</a>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </fieldset>
              {% endif %}
                
            </div>
            <div class="media-body">
              <button class="btn btn-warning" type="submit">Up!</button>
            </div>
          </div>
      </form>
    </div>
  {% endif %}
    
{% endblock content %}

{% block js %}
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>
    $(document).ready(function() {
      $('.js-select').select2();
    });
  </script>
{% endblock js %}

wds_store/templates/menu/filtrar_items.html
{% extends "base.html" %}
{% load static %}
{% block style %}
  <link rel="stylesheet" href="{% static 'css/filtrar_items.css' %}">
{% endblock style %}
{% block content %}

  {% if modelo == 'producto' %}
    <div class="media row row-cols-1 row-cols-md-3 g-4">
      <div class="media mt-0">
        <div class="media-body btn-group dropdown">
          <a class="btn btn-lg" href="{% url 'items:create' 'talla' objeto %}"><strong>Tallas</strong></a>
          <button class="btn btn-lg dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false"></button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenu2">
            {% for talla in tallas %}
              <li class="btn-group mb-1">
                <a class="dropdown-item" href="{% url 'items:itemlist' 'talla' talla %}">{{ talla }}</a>
                <a class="btn btn-sm" href="{% url 'items:update' 'talla' talla 'objeto' %}">Update</a>
                <a class="btn btn-sm delete" href="{% url 'items:delete' 'talla' talla %}">Delete</a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    {% for item in items  %}
      {% for imagen in imagenes %}
        
        {% if item.id == imagen.item.id %}
          <br>
          <div class="media">
            <div class="media-body">
              <a id="producto" href="{{ imagen.imagen.url }}">
                <img src="{{ imagen.imagen.url }}" alt="imagen.id">
              </a>
            </div>
            <div class="media-body">
              <a class="btn btn-info" href="{% url 'items:update' modelo item slugname %}">
                Update!
              </a>
            </div>
            <div class="media-body">
              <a class="btn btn-danger" href="{% url 'items:delete' modelo item slugname %}">
                Delete!
              </a>
            </div>
          </div>
        {% endif %}
          
      {% endfor %}
    {% endfor %}
  {% endif %}
  {% for imagen in imagenes  %}
    <br>
    <div class="media">
      <div class="media-body">
        <a id="producto" href="{{ imagen.imagen.url }}">
          <img src="{{ imagen.imagen }}" alt="imagen.id">
        </a>
    </div>
  {% endfor %}
{% endblock content %}

wds_store/templates/menu/index&listados.html
{% extends "base.html" %}
{% load static %}
{% block style %}
  <link rel="stylesheet" href="{% static 'css/index&listados.css' %}">
{% endblock style %}
{% block content %}
  <div class="media row row-cols-1 row-cols-md-3 g-4">
    <div class="media mt-0">
      <div class="btn-group">
        <div class="media-body btn-group dropdown">
          <a class="btn btn-lg" href="{% url 'items:create' 'producto' '...' %}"><strong>Productos</strong></a>
          <button class="btn btn-lg dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false"></button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenu2">
            {% for producto in productos %}
              <li class="btn-group mb-1">
                <a class="dropdown-item" href="{% url 'items:itemlist' 'producto' producto %}">{{ producto }}</a>
                <a class="btn btn-sm" href="{% url 'items:update' 'producto' producto '...' %}">Update</a>
                <a class="btn btn-sm delete" href="{% url 'items:delete' 'producto' producto %}">Delete</a>
              </li>
            {% endfor %}
          </ul>
        </div>
        <div class="media-body btn-group dropdown" id="expandir_button">
          <a class="btn btn-lg" href="{% url 'items:create' 'color' '...' %}"><strong>Colores</strong></a>
          <button class="btn btn-lg dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false"></button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenu2">
            {% for color in colores %}
              <li class="btn-group mb-1">
                <a class="dropdown-item" href="{% url 'items:itemlist' 'color' color %}">{{ color }}</a>
                <a class="btn btn-sm" href="{% url 'items:update' 'color' color '...' %}">Update</a>
                <a class="btn btn-sm delete" href="{% url 'items:delete' 'color' color %}">Delete</a>
              </li>
            {% endfor %}
          </ul>
        </div>
        <div class="media-body btn-group dropdown">
          <a class="btn btn-lg" href="{% url 'items:create' 'celebracion' '...' %}"><strong>Celebraciones</strong></a>
          <button class="btn btn-lg dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false"></button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenu2">
            {% for celebracion in celebraciones %}
              <li class="btn-group mb-1">
                <a class="dropdown-item" href="{% url 'items:itemlist' 'celebracion' celebracion %}">{{ celebracion }}</a>
                <a class="btn btn-sm" href="{% url 'items:update' 'celebracion' celebracion '...' %}">Update</a>
                <a class="btn btn-sm delete" href="{% url 'items:delete' 'celebracion' celebracion %}">Delete</a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}